### ISSUE TITLE
Crash on web socket disconnect - Wrap optional safely ?

### ISSUE THREAD

**Issue by hemantasapkota** [pusher-community/pusher-websocket-swift#1]
Thanks for working this library. On websocket disconnect event, the app crashes because error object ins't unwrapped safely.
```
println("Websocket is disconnected: \(error!.localizedDescription)")
```
Shouldn't this be  ```error?.localizedDescription``` ?

Thanks

**Comment by hamchapman** [comment]
I know this is old but I think this is now fixed / not a problem seeing as I have:

```swift
if let error = error {
    println("Websocket is disconnected: \(error.localizedDescription)")
}
```
