### ISSUE TITLE
Carthage Build Fails

### ISSUE THREAD

**Issue by cocoahero** [pusher-community/pusher-websocket-swift#15]
Carthage fails to build the framework with the following error:

> Failed to discover shared schemes in project iOS Example.xcodeproj—either the project does not have any shared schemes, or xcodebuild never returned

**Comment by hamchapman** [comment]
I'll try and take a look at this over the weekend

**Comment by hamchapman** [comment]
Sorry I haven't managed to yet - I'm going to take a look this evening

**Comment by hamchapman** [comment]
This should all be fixed now. Let me know if it's not working for you
