### ISSUE TITLE
iOS 9 and ReachabilitySwift

### ISSUE THREAD

**Issue by lggdance** [pusher-community/pusher-websocket-swift#16]
Hey guys, there is a compile error with ReachabilitySwift and I can't seem to fix it. Could you update the files and merge the new branches perhaps please? :)

**Comment by hamchapman** [comment]
Bumped version to 0.1.3 which includes fixes to work with latest versions of the pod dependencies.

Let me know if you're hitting any more problems.

I still need to make a few updates to the README, add a CHANGELOG, refactor a few bits of code, and add support for tvOS (and maybe watchOS?). Those last two depend on this first though: https://github.com/krzyzanowskim/CryptoSwift/pull/168
