### ISSUE TITLE
update NSData Extension

### ISSUE THREAD

**Issue by andyyhope** [pusher-community/pusher-websocket-swift#3]
let signature = NSData.withBytes(hmac!).hexString
should be
            let signature = NSData.withBytes(hmac!).toHexString
PusherSwift.swift : Line 373
Cannot compile unless this is fixed

**Comment by hamchapman** [comment]
I'll update this today. Thanks for the spot

**Comment by andyyhope** [comment]
You havent updated your Podspec, currently it still looks for hexString
