### ISSUE TITLE
Swift String Manipulation EXC_BAD

### ISSUE THREAD

**Issue by andyyhope** [pusher-community/pusher-websocket-swift#5]
Apps been crashing when switching to Release build. Specifically PusherSwift.swift at line 66

    func constructUrl(key: String, options: PusherClientOptions) -> String {
    var url = ""
    if let encrypted = options.encrypted where !encrypted {
        url = "ws://ws.pusherapp.com:80/app/\(key)"
    } else {
        url = "wss://ws.pusherapp.com:443/app/\(key)"
    }
    url += "?client=pusher-swift&version=\(VERSION)&protocol=\(PROTOCOL)"
    return url
}

This is a known bug with the Swift 1.2 compiler on Xcode 6.3. See...
http://stackoverflow.com/questions/24208594/swift-string-manipulation-causing-exc-bad-access

Fix: On line 67, specify String type of url.
````var url: String = ""````

**Comment by andyyhope** [comment]
Sorry, still crashes. Instead change the return to this
````return "\(url)?client=pusher-swift&version=\(VERSION)&protocol=\(PROTOCOL)"````

**Comment by hamchapman** [comment]
Thanks @andyyhope !
