### ISSUE TITLE
Cocoapods

### ISSUE THREAD

**Issue by weilsonwonder** [pusher-community/pusher-websocket-swift#8]
Hi, 

I'm having compatibility issues with compiling Starscream on your dependencies. Possible to change it to 1.0.0? Likely due to swift 2.0 upgrade.

**Comment by hamchapman** [comment]
Yep, I imagine that's the problem. I'll push out a new version today that is for 2.0 which should make everything a lot simpler in terms of installation now that 2.0 is the standard version

**Comment by weilsonwonder** [comment]
thanks!

**Comment by hamchapman** [comment]
I've pushed 0.1.2 to Cocoapods trunk so this should now be working. Let me know if that's not the case for you.
